table dim_date
	lineageTag: e4287b8b-a60e-4942-baab-c71cbc6f556d

	column issue_date_id
		dataType: int64
		formatString: 0
		lineageTag: 31fa37b8-c868-47bb-91d8-fcae5e11ad22
		summarizeBy: none
		sourceColumn: issue_date_id

		annotation SummarizationSetBy = Automatic

	column issue_d
		dataType: string
		lineageTag: a6acf7ea-a058-4594-9a78-5cac036c0bb4
		summarizeBy: none
		sourceColumn: issue_d

		annotation SummarizationSetBy = Automatic

	column issue_year
		dataType: int64
		lineageTag: e9a15e6d-d893-4e33-8a63-b9d08f0a7e0c
		summarizeBy: none
		sourceColumn: issue_year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column issue_month
		dataType: string
		lineageTag: 36901eda-3fa4-4fad-9632-f3bf7c5abdd1
		summarizeBy: none
		sourceColumn: issue_month

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source = ```
				let
				    Origen = Odbc.DataSource("driver={SQLite3 ODBC Driver};database=C:\Users\Ary Palacios\Desktop\Proyecto riesgo SQL\lending_club.db;", [HierarchicalNavigation=true]),
				    dim_date_Table = Origen{[Name="dim_date",Kind="Table"]}[Data],
				    #"Filas filtradas" = Table.SelectRows(dim_date_Table, each [issue_date_id] <> null and [issue_date_id] <> ""),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas", {"issue_date_id"}),
				    Cols = Table.ColumnNames(#"Duplicados quitados"),
				    Transformaciones = List.Transform(Cols, each 
				        if Text.EndsWith(_, "_id") or _ = "id" or _ = "issue_year" then {_, Int64.Type}
				        else {_, type text}
				    ),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Duplicados quitados", Transformaciones, "en-US")
				in
				    #"Tipo cambiado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

